import { Inter } from "next/font/google";
import type { Metadata } from "next";
import SideBar from "@/components/SideBar/SideBar";
import { Grid } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Grid container spacing={2}>
          <Grid xs={2}>
            <SideBar />
          </Grid>
          <Grid xs={10}>{children}</Grid>
        </Grid>
      </body>
    </html>
  );
}
